version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: api-container
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  client:
    build:
      context: ./client
    container_name: client-container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
